- pkg/config/config.go
- pkg/server/httpserver.go
- test/go-report-card-test/Dockerfile
- test/go-report-card-test/run-report-card-test.sh
increase goreportcard threshold and fix fmt errors
*Testing*
make clean && make build && make test succeeded
> increase goreportcard threshold and fix fmt errors

- README.md
https://github.com/aws/amazon-ec2-metadata-mock/issues/8
update readme to reflect launch status
> update readme to reflect launch status

- README.md
Adding installation commands for pre-release v0.9.0.
*Note: need to hard-code version for pre-release because pre-releases will not be in '/latest/' download path.*
*Issue #, if available:* #8 
* Updating README with pre-release installation instructions
> Update README.md with pre-release installation

- .travis.yml
* License test and sync read me to dockerhub scripts will execute on new Releases
> Update travis to sync readme with dockerhub & run license test on release

- README.md
Testing:
- Verified all links download correct asset by comparing with file size
- Verified MacOS and Linux builds by downloading binary and running on laptop and ec2, respectively
*Description of changes:* N/A
> Up readme installation version

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/ci/configmap-values.yaml
- helm/amazon-ec2-metadata-mock/ci/custom-service-config-values.yaml
- helm/amazon-ec2-metadata-mock/ci/default-values.yaml
- helm/amazon-ec2-metadata-mock/templates/NOTES.txt
- helm/amazon-ec2-metadata-mock/templates/service.yaml
- helm/amazon-ec2-metadata-mock/templates/tests/test-aemm-service.yaml
- helm/amazon-ec2-metadata-mock/templates/tests/test-config-map.yaml
- helm/amazon-ec2-metadata-mock/values.yaml
* minor fixes after running linter test
* fixing service name (previously, it was same as the release name)
* adding helm e2e tests and custom values files for tests
*To follow:*
* script to run helm tests being added in this PR.
> Add Helm e2e tests and minor fixes to the chart

- .travis.yml
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- test/helm/chart-test.sh
* fix helm readme
* add helm tests to travis for multiple K8s versions
* minor changes to test script
> Add Helm tests to Travis

- Makefile
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- test/helm/chart-test.sh
* add helm linting to build target
* minor changes to helm test script and readme
> add helm linting to build target

- Makefile
- README.md
- docs/defaults.md
- scripts/build-binaries
- test/helm/chart-test.sh
* minor changes to documentation and binary generation
* add defaults.md for clarity 
> minor changes to documentation, binary generation and build targets

- scripts/upload-resources-to-github
> fix release script

- scripts/upload-resources-to-github
> fix release script - part2

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
* N/A
* updating versions for app and chart for v1.0.0 release
> v1.0.0 version updates

- scripts/generate-helm-chart-archives
None 
* helm release script generated helm archive with dir structure `helm/amazon-ec2-metadata-mock` - this was fixed to remove the parent dir `helm`
> fix  helm release script

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
N/A
* update readmes/ helm charts for v1.0.1 release
> Release prep for v1.0.1

- Makefile
- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
- scripts/create-local-tag-for-release
- scripts/update-versions-for-release
- scripts/validators/release-version-validator
N/A
* Chart versioning related changes:
* remove appVersion in chart (appVersion is an optional field and informational only) 
* updates release version scripts to accommodate changes to chart versioning
* Automation of release prep: 
* automate release prep - see make release-prep* targets
* release prep for v1.1.0
> update release version scripts to accommodate changes to chart versioning

- scripts/create-local-tag-for-release
N/A
* making script to create new release tag idempotent
> making script to create new release tag idempotent

- Makefile
- scripts/prepare-for-release
* make make targets consistent
* improve release prep automation script by adding options for draft mode, repo and user prompt before creating pr
Test PR: 
https://github.com/pdk27/amazon-ec2-metadata-mock-1/pull/13
Script output: shared internally
> release prep automation

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
🥑🤖 Auto-generated PR for v1.1.1 release. Updating release versions in repo.
> 🥑🤖 v1.1.1 release prep

- .travis.yml
- Makefile
- README.md
- docs/configuration.md
- helm/amazon-ec2-metadata-mock/README.md
- scripts/create-local-tag-for-release
- scripts/prepare-for-release
- scripts/update-versions-for-release
- scripts/upload-resources-to-github
- test/e2e/run-tests
- test/helm/chart-test.sh
- test/readme-test/run-readme-spellcheck
- test/readme-test/spellcheck-Dockerfile
- test/shellcheck/run-shellcheck
N/A
- Add Shellcheck to check for errors in bash files
- Fix errors found in bash files
- Add spellcheck to check markdown files
- Fix spelling errors in markdown files
> add shellcheck and spellcheck

- .travis.yml
- Makefile
- scripts/sync-to-aws-homebrew-tap
N/A
- Sync AEMM to the aws/tap homebrew repo
> sync to homebrew aws/tap

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
🥑🤖 Auto-generated PR for v1.1.2 release. Updating release versions in repo.
> 🥑🤖 v1.1.2 release prep

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
🥑🤖 Auto-generated PR for v1.1.3 release. Updating release versions in repo.
> 🥑🤖 v1.1.3 release prep

- scripts/sync-to-aws-homebrew-tap
N/A
- Homebrew sync script was not updating the fork w/ upstream changes causing issues when upstream changes.
> homebrew sync script updates fork with upstream changes

- pkg/cmd/cmdutil/cmdutil.go
- pkg/cmd/root/root.go
- pkg/config/config.go
- pkg/config/defaults/aemm-metadata-default-values.json
- pkg/config/dynamic.go
- pkg/config/types.go
- pkg/mock/dynamic/dynamic.go
- pkg/mock/dynamic/types/types.go
- pkg/mock/listmocks/listmocks.go
- test/e2e/cmd/dynamic-test
- test/e2e/cmd/root-test
- test/e2e/cmd/static-test
- test/e2e/golden/dynamic_paths.golden
- test/e2e/testdata/aemm-config-integ.json
- test/e2e/testdata/output/aemm-config-used.json
#70 
Add /latest/dynamic/instance-identity/document for simulate instance-identity. 
> add /latest/dynamic/instance-identity/document

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
🥑🤖 Auto-generated PR for v1.2.0 release. Updating release versions in repo.
> 🥑🤖 v1.2.0 release prep

- README.md
- scripts/validators/readme-validator
*Issue #, if available:* #78  -- an example of using integrating AEMM
*Description of changes:* 
* adding `Integrations` to readme w/NTH e2e test example
* fixing path in readme-validator (used to live in `scripts` dir)
> Integr8 readme

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
🥑🤖 Auto-generated PR for v1.3.0 release. Updating release versions in repo.
> 🥑🤖 v1.3.0 release prep

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
🥑🤖 Auto-generated PR for v1.4.0 release. Updating release versions in repo.
> 🥑🤖 v1.4.0 release prep

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
🥑🤖 Auto-generated PR for v1.4.1 release. Updating release versions in repo.
> 🥑🤖 v1.4.1 release prep

- .travis.yml
- Dockerfile
- Dockerfile.windows
- README.md
- go.mod
> upgrade to go1.15

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
🥑🤖 Auto-generated PR for v1.5.0 release. Updating release versions in repo.
> 🥑🤖 v1.5.0 release prep

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
🥑🤖 Auto-generated PR for v1.6.0 release. Updating release versions in repo.
> 🥑🤖 v1.6.0 release prep

- BUILD.md
- CONTRIBUTING.md
- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
- scripts/prepare-for-release
N/A
Replace references to master branch to main
> replace master w/ main

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
🥑🤖 Auto-generated PR for v1.7.0 release. Updating release versions in repo.
> 🥑🤖 v1.7.0 release prep

- helm/amazon-ec2-metadata-mock/README.md
* N/A
* Include download instructs in helm readme
> update helm readme

- helm/amazon-ec2-metadata-mock/templates/deployment.linux.yaml
- helm/amazon-ec2-metadata-mock/templates/deployment.windows.yaml
- helm/amazon-ec2-metadata-mock/values.yaml
* #102 
* adding resources block
*Testing:*
* Tested locally and saw resources request/limits take effect:
> add resources block

- README.md
- pkg/config/defaults/aemm-metadata-default-values.json
- pkg/config/types.go
- test/e2e/golden/dynamic_paths.golden
- test/e2e/testdata/output/aemm-config-used.json
* N/A, adding more paths
* add `instance-identity/pkcs7`
* add `instance-identity/signature`
*Verification:*
* public docs [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-categories.html)
* Verified content using my EC2 instance:
**IMDS**: instance-identity/pkcs7
```
[ec2-user~]$ curl -i http://169.254.169.254/latest/dynamic/instance-identity/pkcs7
HTTP/1.0 200 OK
Accept-Ranges: bytes
Content-Length: 1118
Content-Type: text/plain
Date: Tue, 10 Nov 2020 21:57:42 GMT
Last-Modified: Wed, 21 Oct 2020 22:34:17 GMT
Connection: close
Server: EC2ws
```
**AEMM**: instance-identity/pkcs7
```
$ curl -i localhost:1338/latest/dynamic/instance-identity/pkcs7
HTTP/1.1 200 OK
Content-Type: text/plain
Date: Wed, 11 Nov 2020 …
```
> adding pkcs and signature paths

- README.md
- pkg/config/defaults/aemm-metadata-default-values.json
- pkg/config/types.go
- test/e2e/golden/dynamic_paths.golden
- test/e2e/testdata/output/aemm-config-used.json
* N/A
* adding the last dynamic path 🎉 
> add fw instance monitoring

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
🥑🤖 Auto-generated PR for v1.8.0 release. Updating release versions in repo.
> 🥑🤖 v1.8.0 release prep

- .github/workflows/ci.yaml
- scripts/prepare-for-release
- scripts/upload-resources-to-github
- test/e2e/run-tests
- test/go-report-card-test/run-report-card-test.sh
- test/helm/chart-test.sh
N/A
- Move to github actions
https://github.com/bwagner5/aemm-test/runs/1444326486?check_suite_focus=true
> gh actions

- Makefile
N/A
fix docker login commands for gh actions
> fix docker login commands for gh actions

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
🥑🤖 Auto-generated PR for v1.8.1 release. Updating release versions in repo.
> 🥑🤖 v1.8.1 release prep

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
🥑🤖 Auto-generated PR for v1.9.0 release. Updating release versions in repo.
> 🥑🤖 v1.9.0 release prep

- .github/workflows/ci.yaml
Adding aws creds to GitHub Actions file. These are used for uploading images to ecr public
> Add aws credentials to github actions

- README.md
- helm/amazon-ec2-metadata-mock/Chart.yaml
- helm/amazon-ec2-metadata-mock/README.md
- helm/amazon-ec2-metadata-mock/values.yaml
🥑🤖 Auto-generated PR for v1.9.1 release. Updating release versions in repo.
> 🥑🤖 v1.9.1 release prep

- .github/workflows/stale.yaml
> Add stalebot

- .github/workflows/release.yaml
- Makefile
- helm/amazon-ec2-metadata-mock/README.md
- scripts/sync-to-aws-eks-charts
Issue #, if available: https://github.com/aws/amazon-ec2-metadata-mock/issues/157
* Adds [sync-to-aws-eks-charts](https://github.com/aws/aws-node-termination-handler/blob/main/scripts/sync-to-aws-eks-charts) from NTH and updates naming, repo link, etc.
* Updates gh actions and makefile
* Updates documentation
> Upload Helm to eks-charts

- .github/workflows/build-and-test.yaml
**Issue #, if available:** N/A, we experience transient failures running early AM so experimenting with a more "active" time
> Update daily runs to afternoon

- USAGE.md
- docs/usage.md
- test/shellcheck/run-shellcheck
Description of changes: Consolidates `usage` docs, reformat, and add some content to Brandon's use case.
> Update Usage docs

- .github/workflows/release.yaml
There are syntax errors in the `release.yaml` workflow, fixed these errors.
> Fixed syntax errors

- .github/workflows/build-and-test.yaml
- test/helm/chart-test.sh
Upgrade ubuntu version in wf to `ubuntu-24.04`
> Upgrade ubuntu version in wf

- .github/workflows/build-and-test.yaml
- .github/workflows/release.yaml
Fix windows ver to windows-2025
> Fix windows ver
