Makefile, scripts/build-binaries, scripts/build-docker-images, scripts/generate-k8s-yaml, scripts/push-docker-images, scripts/sync-readme-to-dockerhub, scripts/upload-resources-to-github
* Porting scripts/  from nth to aemm  for **make release** target which will be called via TravisCi
* Updated Makefile with corresponding targets
* Added MacOS and Windows to SUPPORTED_PLATFORMS
*Testing:*
* Pulled in [helm changes](https://www.github.com/aws/amazon-ec2-metadata-mock/pull/6) locally
* Changed *IMG* to my private dockerhub repo
* Created test release+tag in AEMM GitHub repo
* Ran `make clean` && `make release` && `make test` successfully
=> Adding scripts for release target

.travis.yml, pkg/config/config.go
- Adding .travis.yml
- replaced helm-sync-test with e2e-test
- removed Deploy::sync-readme-to-dockerhub for now as README is too long to upload via API
- Fixed spacing in config.go to pass go-report-card
*Testing:*
- make clean && make build && make test succeed
=> Adding travis.yml for TravisCI integration

.travis.yml, BUILD.md, README.md, go.mod
* Upgrading go version to latest
* Updated travis.yml's make e2e-test target. It requires reference to go and gomodule because a build is kicked off beforehand (via make compile)
*Testing:*
* make clean && make build && make test succeeds
* kicked off custom build on travisci with travis.yml updates and tests pass
=> Upgrade go version to v1.14

test/license-test/run-license-test.sh
* Updating run-license-test to use **make build-binaries** instead of **make build** because the latter will cause travisci to fail the build without explicit references to go in the yml file. The former executes the build in a docker container. 7th build is definitely going to pass!!
*Testing:*
- make clean && make build && make test
- make license-test passes
=> Updating run-license-test

.travis.yml, Makefile, README.md, docs/configuration.md, docs/usage.md, scripts/sync-readme-to-dockerhub, test/readme-validator
* Updated README.md to be within DockerHub upload character count limit (25000). Updated char count: 20911
* Added *readme-validator* to ensure readme files are below max char count-- this will be invoked by **travisci** for all PRs
* Updated sync-readme-to-dockerhub to use $DOCKERHUB_PASSWORD instead of TOKEN as the token is **not** supported per [this issue](https://github.com/peter-evans/dockerhub-description/issues/10)
* Kept common use cases and high-level descriptions in main README and moved advanced usage and configuration details to docs/usage.md and docs/configuration.md, respectively.
* When adding more installation methods, we can create installation.md at that time if we are approaching char limit in main README.
* …
=> Reorganizing README to be compliant with DockerHub upload limit

README.md
Adds a section about Docker to the readme. I noticed there's a docker image and tried it out, but initially couldn't get it to work because on Mac (and Windows), the default hostname won't work.
=> Add Docker notes to README

Makefile, helm/amazon-ec2-metadata-mock/Chart.yaml, test/helm/chart-test.sh, test/helm/ct.yaml, test/helm/kind-config.yaml
* add script to test helm charts for linting, validation, version bump and installation
* bumping app version and chart version in helm chart
* adding targets for helm tests in makefile
*Test* 
make clean && make build && make test
make helm-lint-test 
=> add test script for helm e2e tests along with makefile targets

pkg/cmd/root/root.go, pkg/config/server.go
* change default hostname so zero config cli works on docker
Readme changes will follow in a subsequent PR. 
*Related PRs*: https://github.com/aws/amazon-ec2-metadata-mock/pull/19
=> change default hostname so zero config cli works on docker

README.md, docs/usage.md, pkg/cmd/cmdutil/cmdutil.go, pkg/cmd/root/root_test.go, pkg/cmd/scheduledevents/scheduledevents.go, pkg/cmd/spotitn/spotitn.go, pkg/cmd/spotitn/spotitn_test.go, pkg/config/config.go, pkg/config/types.go, pkg/mock/scheduledevents/internal/types/types.go, pkg/mock/scheduledevents/scheduledevents.go, test/e2e/cmd/scheduledevents-test, test/e2e/cmd/spotitn-test
- Updated command name for spot and aliases for both spot and scheduledevents
- If there's anything wrong with importing override config file (invalid json, can't be found, etc.), then application exits
- Corrected EventId capitalization in maintenance events
*Testing:*
- make test passes
- tried invalid json and non-existent json and application exits as expected
- updated command integration tests to use both command name and aliases
- updated ReadMe content with correct command aliases
=> Addressing issues before v1.0.0

.travis.yml, Makefile, README.md, helm/amazon-ec2-metadata-mock/Chart.yaml, helm/amazon-ec2-metadata-mock/README.md, helm/amazon-ec2-metadata-mock/values.yaml, scripts/generate-helm-chart-archives, scripts/generate-k8s-yaml, scripts/update-versions-for-release, scripts/upload-resources-to-github, test/helm/helm-app-version-test.sh
* add helm scripts for release - generation of helm chart archive
* modify release scripts to include helm
* add test for release version in helm to ensure we are testing against the latest version of AEMM when helm-e2e-test is run
* update appVersion from '0.9.3' to 'v0.9.3'
* add a script to be run manually to update the AEMM version and helm chart versions in various files
* release prep for v0.9.4 - this will be overwritten once this PR is merged.
* updated helm-app-version-test to use `git tag` instead of result from `git describe` 
=> include helm in the release process

README.md, docs/configuration.md, docs/usage.md, helm/amazon-ec2-metadata-mock/Chart.yaml, helm/amazon-ec2-metadata-mock/README.md, helm/amazon-ec2-metadata-mock/templates/daemonset.yaml, helm/amazon-ec2-metadata-mock/templates/tests/test-aemm-service.yaml, helm/amazon-ec2-metadata-mock/values.yaml, pkg/cmd/root/root.go, pkg/cmd/spotitn/spotitn.go, pkg/cmd/spotitn/spotitn_test.go, pkg/mock/spotitn/config/config.go, pkg/mock/spotitn/internal/types/types.go, pkg/mock/spotitn/spotitn.go, test/e2e/cmd/spotitn-test, test/e2e/testdata/aemm-config-integ.json, test/e2e/testdata/output/aemm-config-used.json
*Issue #, if available:* 
Spot interrupt notice used 'instance-action' as the key when it should be 'action': https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html#instance-action-metadata
* Updated spot itn response key from instance-action to action
* Updated flag for consistency
* Updated docs to reflect these changes
* Updated helm chart version
*Testing:*
* make clean && make test
* e2e tests verify the update flag and env var for spot action
=> Correcting spot interrupt notice response

test/e2e/cmd/spotitn-test, test/e2e/run-tests
* TravisCi (and testing locally) sometimes error out on e2e-tests for a couple reasons:
1. after calling clean_up, the next test is kicked off too quickly resulting in 'address already in use'
2. when comparing timestamps, the number of seconds is off by 1
1. added a sleep to clean_up after calling kill as a buffer before kicking off next test
2. instead of exact comparison, see if times are within specified range (using 5 seconds)
=> Fixing transient issues in integration tests

README.md, docs/usage.md, pkg/cmd/cmdutil/cmdutil.go, pkg/cmd/root/root_test.go, pkg/cmd/scheduledevents/scheduledevents.go, pkg/cmd/scheduledevents/scheduledevents_test.go, test/e2e/cmd/scheduledevents-test
**Issue #, if available:**
* typing 'scheduledevents' as a cmd is clunky and poor cx
* not all 'events' are scheduled; some can be historical
* events/maintenance/history path will be supported in the future
* update cmd name to 'events'
* update docs to reflect new cmd name
* keeping 'scheduledevents' as a supported alias
* using all aliases for 'events' in integration tests
=> changing scheduledevents cmd name to events

pkg/config/defaults/aemm-metadata-default-values.json, pkg/mock/scheduledevents/scheduledevents.go, pkg/mock/static/types/types.go
* Addressing inconsistencies with some metadata responses
* Updated responses for the following paths:
* iam/info --> first letter of keys are now capitalized
* iam/security-credentials/baskinc-role --> first letter of keys are now capitalized
* events/maintenance/scheduled --> returns an array of events
=> correcting more responses to align with metadata service

pkg/config/metadata.go, pkg/mock/static/static.go, pkg/server/httpserver.go
**Issue:**
* /latest/meta-data/elastic-inference/associations/eia-bfa21c7904f64a82a21b9f4540169ce1 path returned empty AND malformed response 
* added functionality to correctly populate these nested structs
* added response type that formats to look like JSON but actually returns content type text/plain
* elastic inference accelerator path correctly returns the following:
`{"version_2018_04_12":{"elastic-inference-accelerator-id":"eia-bfa21c7904f64a82a21b9f4540169ce1","elastic-inference-accelerator-type":"eia1.medium"}}`
=> fixing elastic inference accelerator response

.travis.yml, README.md, helm/amazon-ec2-metadata-mock/Chart.yaml, helm/amazon-ec2-metadata-mock/README.md, helm/amazon-ec2-metadata-mock/values.yaml
- updating app and chart versions for v0.9.5 release
- removed e2e helm tests in travis.yml due to race condition of testing versions
=> bumping app and chart versions for release

.travis.yml, Makefile, scripts/upload-resources-to-github
This reverts commit 75e0677d6ba6c32b5b2b80baf84443d56ef98861.
**Issue:**
* These changes to release target are blocking v1.0.0 release
* Couple issues found so far:
* **Github release:**
```Uploading release assets for release id '27616643' to Github
1. individual-resources.tar
❌ Upload failed with response code 422 and message 
{"message":"Validation Failed","request_id":"B860:3AD4:3B6C24:489BCD:5EE94D54","documentation_url":"https://developer.github.com/v3","errors":[{"resource":"ReleaseAsset","code":"custom","field":"size","message":"size is not included in the list"}]} ❌
Makefile:79: recipe for target 'upload-resources-to-github' failed
make: *** [upload-resources-to-github] Error 1
The command "make release" exited with 2.
```
* indicates something may be wrong with the path
* …
=> Revert "improve release script and Travis build order  (#34)"

README.md, helm/amazon-ec2-metadata-mock/Chart.yaml, helm/amazon-ec2-metadata-mock/README.md, helm/amazon-ec2-metadata-mock/templates/tests/test-config-map.yaml, helm/amazon-ec2-metadata-mock/values.yaml
* bumping app and helm chart versions for v0.9.6 release
* fixed helm test now that it's testing against updated AEMM
* this is bug that should be addressed when fixing race condition in helm e2e
=> bump versions for release and fix helm test

scripts/generate-k8s-yaml
N/A
The plain resource files generated from the helm chart included the helm e2e resources as well. 
This PR removes those resources by adding the `--no-hooks` flag to the `helm template` executions.
=> do not generate helm tests in plain k8s resource files

.travis.yml, Makefile, scripts/upload-resources-to-github
* No issue #
* **issue:** when trying to execute release targets with improvements (#34) , `Github Release` and `Docker Release` jobs would fail
* *ex:* https://travis-ci.org/github/aws/amazon-ec2-metadata-mock/jobs/699105736
* *root cause:* Building of assets/artifacts was happening in a separate job which for travis means a separate VM; therefore, the release jobs would not have access to or be able to locate the assets
* Reverted (#41 ) which brings back release improvements (#34) **minus** the helm e2e tests as there is a separate issue with versioning
* Updated `make release` to include `build-release-assets`
* Updated `Docker Release` to execute `make release-docker`
*Testing:*
* Created a release on my fork which executed release …
=> Fixing release targets for updated release scripts

pkg/mock/imdsv2/imdsv2_test.go, pkg/mock/imdsv2/tokengenerator.go, pkg/mock/imdsv2/tokenvalidator.go
**Issue:**
* When requesting a token for imdsv2, the response should contain the token TTL header, `X-aws-ec2-metadata-token-ttl-seconds`
* Added TTL header to response
* Updated unit tests
* Some additional logging
**Testing:**
* **Before Fix:**
```
curl -X PUT -v "localhost:1338/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 1338 (#0)
> PUT /latest/api/token HTTP/1.1
> Host: localhost:1338
> User-Agent: curl/7.54.0
> Accept: */*
> X-aws-ec2-metadata-token-ttl-seconds: 21600
>
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Fri, 26 Jun 2020 15:38:08 GMT
< Content-Length: 44
<
* Connection #0 to host localhost left intact …
```
=> Imdsv2 fixn

helm/amazon-ec2-metadata-mock/Chart.yaml, helm/amazon-ec2-metadata-mock/templates/daemonset.yaml, helm/amazon-ec2-metadata-mock/values.yaml
* When integrating with NTH, it's necessary to specify tolerations and additional args ('spot' vs. 'events')
* Adds tolerations and arguments to values.yaml and consumes them in daemonset template
* Update node selector usage
*Testing:*
* Tested locally with NTH integration tests successfully using:
```
helm upgrade --install $CLUSTER_NAME-aemm /Users/crtbry/workplace/go/src/aemm_brycahta_fork_ws/amazon-ec2-metadata-mock/helm/amazon-ec2-metadata-mock/ \
--wait \
--namespace default \
--set servicePort="$IMDS_PORT" \
--set 'tolerations[0].effect=NoSchedule' \
--set 'tolerations[0].operator=Exists' \
--set arguments={spot}
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
=> adding tolerations and args to helm chart

.travis.yml, Makefile, scripts/create-local-tag-for-release, scripts/prepare-for-release
*Description* 
* add script to automate release prep - includes 
1) create and checkout a new branch with the latest tag name
2) update AEMM and Helm chart versions
3) commit release prep changes to new branch  
4) create a PR from the new branch to upstream/master
* modify travis config to run helm e2e tests conditionally
* improve script to create tag for release by sync-ing local tags before tag creation
*Tests*
Sample auto-generated PR - https://github.com/pdk27/amazon-ec2-metadata-mock-1/pull/8
https://github.com/aws/amazon-ec2-metadata-mock/pull/57 (not perfect, but cut to upstream) 
Output of script - shared internally
=> Release prep automation and modify Travis config 

Dockerfile.windows, Makefile
* adding Dockerfile.Windows which can be built and run using Docker on Windows
* Updated Makefile to work with `git-bash` on Windows:
* `tr -d '\040\011\012\015'` removes spaces, tabs, carriage returns, and newlines
* still works on Mac and Linux
*Testing:*
* Launched EC2 instance with *Microsoft Windows Server 2019 with Containers* ami
* Copied these changes to the instance
* In Powershell or Command Util:
* `docker build -f Dockerfile.windows` executes successfully
* `docker run <generated_image>` starts AEMM as expected
=> adding Dockerfile for Windows support

Makefile, scripts/build-binaries
N/A
- Generate tar.gz bin files for more efficient downloads and for use as static bottles for homebrew.
- Generate .zip bin file for windows
=> add tar.gz bin files for linux and mac and a zip'd bin for windows

Makefile, test/helm/chart-test.sh, test/helm/ct.yaml
N/A
* modify make help to include digits
* modify helm chart test config to run chart linting and installation for all charts, remove git upstream sync as we don't care about whether charts changed or not.
* add debug for helm lint
* print chart test config along with script args
*Test*
https://travis-ci.org/github/pdk27/amazon-ec2-metadata-mock-1/builds/707753358 
=> Release automation

.travis.yml, helm/amazon-ec2-metadata-mock/templates/clusterrole.yaml, test/helm/chart-test.sh
**Issue #, if available:**
* No issue #, but NTH PR is failing because current AEMM helm chart's `rules` value for k8s versions 1.12 + 1.13
* https://travis-ci.org/github/aws/aws-node-termination-handler/jobs/709333749
* rules as an empty array to correct parsing error in k8s 1.12 an 1.13
* corrected check on `${!OPTARG}`
* **note: needs to be done in NTH as well**
* Now that NTH uses AEMM for its integ tests, AEMM needs to support the same k8s versions as NTH; therefore adding 1.12 and 1.13 support
**Local Testing:**
* All pass successfully:
* test/helm/chart-test.sh -i -k 1.12
* test/helm/chart-test.sh -i -k 1.13
* test/helm/chart-test.sh -i -k 1.18
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
=> extend support to k8s versions 1.12 and 1.13

scripts/push-docker-images
- No #, but the issue is during AEMM release, the `Docker Release Windows` stage will overwrite existing manifest leaving it populated with **only windows/amd64** and erasing linux distros that were there previously.
- I thought this worked before, but the manifest was cached on my machine from previous upload making it appear as if it were working
* Check for existence of manifest and update PLATFORMS accordingly
* added `--purge` to push to clear local cache
*Testing:*
* very locally tested on my test Dockerhub repo with no local cache this time
*Notes:*
* `--amend` is useless
=> fix push-docker-images logic to populate manifest correctly

scripts/push-docker-images
*Issue #, if available:* 
* During v1.3.0 release the docker manifest was overwritten with Windows image **only** which caused subsequent helm testing to fail due to Linux images not being available.
* enable experimental Docker CLI features **before** running `manifest inspect` to check if manifest exists already. Otherwise, manifest will be overwritten and the following error: `docker manifest inspect is only supported on a Docker cli with experimental cli features enabled`
* related log from v1.3.0 release: https://travis-ci.org/github/aws/amazon-ec2-metadata-mock/jobs/716661941
=> prevent push-docker-images from overwriting existing manifest

scripts/push-docker-images
*Issue #, if available:* 
* this fixes the dockerhub manifest so that subsequent releases **update** and **annotate** manifest correctly without overwriting it
* `MANIFEST_IMAGES` is an array; existing images in the manifest will be added directly here
* using `manifest create --amend` because for-loop is the only way I can get Windows to register multiple manifest images at once
* fixed spacing
* added more `echo` for easier debugging in Travis
*Testing:*
* https://travis-ci.org/github/brycahta/amazon-ec2-metadata-mock/builds/717368709
* ignore the Helm ish
* Test Dockerhub aka Dockershub with all images in manifest: https://hub.docker.com/repository/docker/brycahta/dockershub/tags?page=1
By submitting this pull request, I confirm that you can use, modify, copy, …
=> fixing push-docker-images to update manifest correctly

README.md
N/A
Add Amazon EC2 Spot Instances Integration Roadmap to readme
=> Add Amazon EC2 Spot Instances Integration Roadmap to readme

README.md, helm/amazon-ec2-metadata-mock/README.md, helm/amazon-ec2-metadata-mock/templates/daemonset.linux.yaml, helm/amazon-ec2-metadata-mock/templates/daemonset.windows.yaml, helm/amazon-ec2-metadata-mock/values.yaml, pkg/cmd/root/globalflags/globalflags.go, pkg/cmd/root/root.go, pkg/cmd/root/root_test.go, pkg/config/types.go, pkg/mock/events/events.go, pkg/mock/spot/spot.go, test/e2e/cmd/root-test, test/e2e/testdata/aemm-config-integ.json
This adds a new config setting to specify an RFC3339 timestamp as an alternative to a mock delay. When the timestamp is reached the server will return the mock events or spot interruption.
We use this feature to simulate the interruption of many spot instances at once which requires a better timing than the startup delay
=> Add MockTriggerTime setting to return events and spot interruptions at a specific time

Dockerfile.windows, scripts/prepare-for-release, scripts/push-docker-images, scripts/update-versions-for-release, scripts/upload-resources-to-github, scripts/validators/json-validator, scripts/validators/readme-validator, scripts/validators/release-version-validator, test/e2e/cmd/static-test, test/e2e/run-tests, test/go-report-card-test/run-report-card-test.sh, test/helm/chart-test.sh, test/license-test/gen-license-report.sh, test/shellcheck/run-shellcheck
* addressing warnings from shellcheck
* using `jq` in e2e tests bcuz we're not savages
* corrected json-validator path
=> reconcile shellcheck warnings

test/go-report-card-test/Dockerfile
*Issue #, if available:*  https://github.com/gojp/goreportcard/pull/298
* if `make install` fails, then fall back to manual installation
*Testing:*
* clear Docker cache and `make go-report-card-test` locally:
```
✅ goimports found no formatting errors in go source files
Grade: A+ (100.0%)
Files: 33
Issues: 0
gofmt: 100%
go_vet: 100%
golint: 100%
gocyclo: 100%
ineffassign: 100%
license: 100%
misspell: 100%
```
* Takes ~20sec longer to run now D: 
=> go-report-card installation workaround

Makefile, scripts/prepare-for-release, scripts/sync-to-aws-homebrew-tap
* N/A, just some minor fixes/updates to release automation
* Update how we fetch git tags
* `v1.10.0` will break the current approach. Output of `git tag` will be:
* v1.1.0
* v1.10.0
* v1.2.0
* ... 
* v1.9.0
* then piping output to `tail -1` will return **v1.9.0** as the latest which is **incorrect**
* Correcting repo name in sync-homebrew
* Add spacing for PR confirmation
=> update git tag fetching

.github/workflows/ci.yaml, Makefile, helm/amazon-ec2-metadata-mock/README.md, helm/amazon-ec2-metadata-mock/values.yaml, scripts/draft-release-notes, scripts/ecr-public-login, scripts/install-awscli, scripts/retag-docker-images, test/license-test/run-license-test.sh, test/shellcheck/run-shellcheck
* We are not currently publishing images to public ECR
* Brought over Brandon's NTH ECR changes to AEMM
* Added functionality to `draft-release-notes` to markdown the PR links for cross posting
Output of draft-release-notes:
```
- push images to public ecr (thanks to Bryan™️)
- make fmt [#113](https://github.com/aws/amazon-ec2-metadata-mock/pull/113) (thanks to Brandon Wagner)
- remove CLA [#114](https://github.com/aws/amazon-ec2-metadata-mock/pull/114) (thanks to Brandon Wagner)
- Update types.go [#112](https://github.com/aws/amazon-ec2-metadata-mock/pull/112) (thanks to Julian Martinez)
- fix docker login commands for gh actions [#111](https://github.com/aws/amazon-ec2-metadata-mock/pull/111) (thanks to Brandon Wagner)
- pr template …
```
=> push images to public ecr

Makefile, README.md, scripts/sync-readme-to-ecr-public
* Keep ReadMe NSYNC with ecr public repo
* Add make target to release process
* Update CI badging
Testing:
* `make sync-readme-to-ecr-public` 
* see updated ecr repo docs: https://gallery.ecr.aws/aws-ec2/amazon-ec2-metadata-mock
=> CI Improvements

README.md
Description of changes: point to ecr public instead of dockerhub
=> Update release badge

helm/amazon-ec2-metadata-mock/templates/service.yaml
Please see this stack overflow for more information.
https://stackoverflow.com/questions/51760772/why-is-release-namespace-rendered-empty
`namespace` -> `Namespace`
=> fix(capitalization): namespace is rendered empty

scripts/ecr-public-login
Github Actions comes with aws cli out of the box. The version should support ecr public apis now
Issue #, if available: N/A -- release failing when trying to install aws cli
=> Remove aws cli installation from ecr public script

.github/workflows/ci.yaml, test/helm/chart-test.sh
Issue #, if available: Latest release failed because of a flag that is no longer supported in older k8s versions
Description of changes: upgrading versions to align with NTH
=> test Helm for k8s versions 1.16-1.21

.github/workflows/ci.yaml, Makefile, scripts/sync-readme-to-ecr-public
* Stop syncing ReadMe to DockerHub; leave script for now
* Always sync ReadMe to ECR Public on release
* Do not run Build/Test jobs during release
* Add a periodic to run jobs
*  Currently set to Mon-Fri at 10AM UTC, which is 5AM CDT
Tested on private repo:
*  ✅    buildAndTest did **not** run on release
*  ✅    set periodic to every 6 minutes and saw job scheduled
=> Release improvements

.github/workflows/helm-chart-test.yaml, .github/workflows/release.yaml, test/helm/chart-test.sh
* Helm Chart tests failed during the[ last release](https://github.com/aws/amazon-ec2-metadata-mock/actions/runs/1172364115) for 2 reasons:
* Version 1.20 came to the script as 1.2 and was seen as invalid because the generated var `K8s_1_2` does not exist
* Version 1.21 is invalid
* Pass in k8s version matrix as array of strings so the `0` does not get truncated
* Update to valid version 1.21.1
* No longer run on a release:
* Move into its own GHA workflow file
* Runs every weekday morning at 5AM CDT
* This will test releases the very next morning
Testing:
=> Fix and Update Helm Chart Tests

.github/workflows/helm-chart-test.yaml, test/helm/chart-test.sh, test/helm/mock-ip-count-test/test-pod-404.yaml, test/helm/mock-ip-count-test/test-pod.yaml
* This morning we were throttled by AWS ECR when running Build and Test jobs
* https://github.com/aws/amazon-ec2-metadata-mock/runs/3460517593?check_suite_focus=true
* Use gcr for container repo because we are less likely to be throttled
=> update mock-ip-count test to use images from gcr

Dockerfile
N/A
- Reduce build times by leveraging docker caching layers. Previously, go mod downloads were not cached between os/arch variants because the build args changed which resulted in docker invalidating the go mod download layer.  
- Now, we separate out the go mod download into a separate docker build stage and copy the assets since they are os/arch independent which results in the layer being cached. 
=> cache modules between os and arch build variants

README.md
=> update location of docker image in readme to ECR

README.md, docs/defaults.md, pkg/config/defaults/aemm-metadata-default-values.json, pkg/config/types.go, test/e2e/golden/events_paths.golden, test/e2e/golden/root_paths.golden, test/e2e/golden/spot_paths.golden
Issue https://github.com/aws/amazon-ec2-metadata-mock/issues/158
Add paths into the metadata
```
tags/instance/Name: test-instance
tags/instance/Test: test-tag
```
=> feat: add path tags Name and Test

scripts/prepare-for-release
For some reason, `read -p` doesn't properly print to stdout when invoked
from a golang `exec.Command().Run()`, but `echo` does. Reading from
stdin still works correctly.
=> Fix release script prompt when calling from a golang process

test/license-test/Dockerfile, test/readme-test/spellcheck-Dockerfile
**Issue #, if available:** N/A. The latest ci/cd run failed: https://github.com/aws/amazon-ec2-metadata-mock/actions/runs/1997882752
* aligns golang version with app
* follow best practices for installing a command using `go install`
As of **Go1.18**
```
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
=> Peg versions in Dockerfiles

pkg/config/defaults/aemm-metadata-default-values.json, pkg/mock/userdata/userdata.go, pkg/server/httpserver.go, test/e2e/cmd/userdata-test, test/e2e/testdata/aemm-config-integ.json, test/e2e/testdata/output/aemm-config-used.json
Issue #175
This allows for userdata to be stored as base64 in the JSON.  This allows for lots of things including multi-line, without needing to put in \n.  Tests should be passing.
=> Base64 Userdata

pkg/mock/dynamic/types/types.go, pkg/server/httpserver.go, pkg/server/httpserver_test.go, test/e2e/cmd/dynamic-test, test/e2e/testdata/aemm-config-integ.json
Issue #, if available: https://github.com/aws/amazon-ec2-metadata-mock/issues/179
* change `marketplaceProductCodes` from `string` to `[]string` and formatting logic to align with IMDS 
=> update marketplaceProductCodes to be list of strings

.github/workflows/helm-chart-test.yaml
We [recently changed](https://github.com/aws/amazon-ec2-metadata-mock/pull/181) the `build-and-test` run to 2 PM Central time, and we've seen fewer transient failures since that change. This PR updates the `helm-chart-test` run to the same time in the afternoon.
=> Update helm-chart-test to run in the afternoon

pkg/mock/imdsv2/imdsv2_test.go
Sporadic test suite failures with errors like
```
imdsv2_test.go:47: Expected valid token generation, but was qAnm5A4tWlsq+hk0Ze0Qb/XT8dLb/aXJftHPJorwJnE=
```
Update regex used by the test to include all valid base64 characters.
=> update test regex for base64

README.md, pkg/cmd/asglifecycle/asglifecycle.go, pkg/cmd/asglifecycle/asglifecycle_test.go, pkg/cmd/cmdutil/cmdutil.go, pkg/cmd/root/globalflags/globalflags.go, pkg/cmd/root/root.go, pkg/cmd/root/root_test.go, pkg/config/defaults/aemm-metadata-default-values.json, pkg/config/types.go, pkg/mock/asglifecycle/asglifecycle.go, pkg/mock/root/root.go, test/e2e/cmd/asglifecycle-test, test/e2e/golden/asglifecycle/latest/meta-data/index.golden, test/e2e/testdata/output/aemm-config-used.json
Issue #218
1) Added core functionality for handling /latest/meta-data/autoscaling/target-lifecycle-state GET requests and changing state after set delay or trigger time. 
2) Updated README
3) Added unit tests for asglifecycle subcommand
4) Added e2e tests to test that asglifecycle target-lifecycle-state changes from InService to Terminated after delay
=> added support for asg target-lifecycle-state path

Makefile, scripts/install-amazon-ecr-credential-helper
AEMM release failed earlier due to ECR login failure for windows. We added a new script that fixes this login issue.
=> Added new script that fixes windows ecr login issues

pkg/cmd/root/globalflags/globalflags.go, pkg/cmd/root/root.go, pkg/cmd/root/root_test.go, pkg/config/types.go, pkg/server/httpserver.go, pkg/server/swapper.go
In the current version of the amazon-ec2-metadata-mock, the server is started, and everything is static from the moment that it starts. This makes it impossible to make any changes based on outside factors, especially in testing conditions.
As an example - I'd like to combine the usage of this mock with LocalStack. In order to work with LocalStack's EC2 APIs, I need to set up subnets and security groups in my LocalStack container (this can be done on initialization of the tests. However, if the amazon-ec2-metadata-mock container is already running, I cannot update its subnet and security group ids to match the created resources in LocalStack.
This PR adds in config file watching via Viper's built in file-watcher, and adds in functionalities to allow us to reset the …
=> Watch Config File And Reset When Changed

Dockerfile.windows, Makefile
- Use explicit output paths for binary artifacts.
- Test in local by: `make build-release-assets`
=> Fix build-release-assets step in release workflow

test/helm/mock-ip-count-test/test-pod-404.yaml, test/helm/mock-ip-count-test/test-pod.yaml
Fix image for mock ip test.
Google Container Registry is deprecated since 2025/03/18 ([ref](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr)). So our `build-and-test` starts failing.
Change to use red hat's container registry ([ref](https://www.centos.org/download/)).
=> Fix image for mock ip test
